### ISSUE TITLE
TypeError: valueCheck is not a function

### ISSUE THREAD

**Issue by Lurkars** [workadventure/tiled-map-type-guard#7]
Due to #3 I tested now Workadventure with 1.0.2 release. On my maps with Animations I get the following error:
```
TypeError: valueCheck is not a function
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/primitives.ts:186:42
           |     at Array.reduce (<anonymous>)
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/primitives.ts:186:7
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/objects.ts:17:3
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/objects.ts:127:40
           |     at InterfaceStep.ptt (/usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/combinators/functions.ts:21:56)
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/combinators/interface.ts:102:57
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/combinators/functions.ts:11:56
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/combinators/functions.ts:11:66
           |     at /usr/src/app/node_modules/@workadventure/tiled-map-type-guard/node_modules/generic-type-guard/src/primitives.ts:186:42
```

**Comment by moufmouf** [comment]
Hey @Lurkars ,

Sorry, I completely failed to see your issue.
Could you let me know where you see your issue?

I assume you see this in the logs of the "back" service right?
Do you have a link to a map I could test? (I cannot reproduce this with my own test map)

**Comment by Lurkars** [comment]
Okay, I found out that the issue is related to group layers, not animations. If I just put animation layer, everything is fine. For example map, just create a group layer and put another layer inside. Then I get the errors.
